### PR TITLE
Add report template to help user sending issue with reproduce script

### PR DESCRIPTION
**Pull request by benoittgt**
The initial PR was open here : https://github.com/rspec/rspec-core/pull/2485. But it was at the wrong place. 

> After watching the [last talk of Sam at RailsConf](https://youtu.be/VMcMqrpjAjU). [I was wondering](https://github.com/rails/rails/pull/19818) about bug report template [like in Rails](https://github.com/rails/rails/pull/19818) for RSpec.

I [mentioned](https://github.com/rspec/rspec-core/pull/2485#issue-280641697) few issues that I don't have anymore. Thanks for the tips @JonRowe.

### CODE REVIEW

**Comment by JonRowe** [comment]
If we're going to do this, we should probably put it into the right file so its automatically put into pull requests? See https://blog.github.com/2016-02-17-issue-and-pull-request-templates/

**Comment by JonRowe** [comment]
I think I like having the reproduction template as a seperate MD file in the repo, linked to from the read me and issue template

**Comment by benoittgt** [comment]
Ok I added an issue template and updated the contributing guide. Both refer to the report template now. I add to modify the rake task to avoid adding *"This file was generated on..."* on `ISSUE_TEMPLATE.md`.

**Comment by JonRowe** [comment]
Do you want to run the rake task to update the other repos?

**Comment by xaviershay** [comment]
This is awesome, thank you both. LGTM for all repos.

**Pull request merged**
