### PR TITLE
Travis: point at rbx-3.84 on Trusty

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR changes the Rubinius line in the CI matrix.

- use 3.84
- this only works on Travis' Trusty dist, so choose that, explicitly

### CODE REVIEW

**Comment by JonRowe** [comment]
This looks sane but we need this applied against all the other repos via PR (theres command line tools in this repo to help with that)

**Comment by olleolleolle** [comment]
@JonRowe Cool.

Do you usually make a test-run with a single change to Travis config, and _then_ apply the other PRs?

**Comment by JonRowe** [comment]
No, we usually just shotgun because its easier and we need to know what breaks where.

**Comment by olleolleolle** [comment]
@JonRowe Is the order of actions:

1. make a change to this repo,
2. check it in via this PR
3. apply to each repo using the Rake tasks for that

Can you confirm?

**Comment by JonRowe** [comment]
Generally we apply changes to the repo via prs before merging any pr on this repo

**Comment by olleolleolle** [comment]
I tried the rake task. I had limited success.

<details>

<summary>rake travis:create_pr_with_updates</summary>

```
--- ruby/rspec-dev ‹patch-1› » rake travis:create_pr_with_updates
==================================================
# rspec-core
----------------------------------------

==================================================
# rspec-expectations
----------------------------------------

==================================================
# rspec-mocks
----------------------------------------

==================================================
# rspec-rails
----------------------------------------

==================================================
# rspec-support
----------------------------------------

==================================================
# rspec-core
----------------------------------------
git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
git pull --rebase
Already up-to-date.
Current branch master is up to date.

==================================================
# rspec-expectations
----------------------------------------
git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
git pull --rebase
Already up-to-date.
Current branch master is up to date.

==================================================
# rspec-mocks
----------------------------------------
git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
git pull --rebase
Already up-to-date.
Current branch master is up to date.

==================================================
# rspec-rails
----------------------------------------
git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
git pull --rebase
Already up-to-date.
Current branch master is up to date.

==================================================
# rspec-support
----------------------------------------
git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
git pull --rebase
Already up-to-date.
Current branch master is up to date.

==================================================
# rspec-core
----------------------------------------
git checkout -b update-travis-build-scripts-2017-09-07-for-master
Switched to a new branch 'update-travis-build-scripts-2017-09-07-for-master'
git add .
git commit -m 'Updated travis build scripts (from rspec-dev)'
[update-travis-build-scripts-2017-09-07-for-master 3068f07a] Updated travis build scripts (from rspec-dev)
 8 files changed, 11 insertions(+), 10 deletions(-)

==================================================
# rspec-expectations
----------------------------------------
git checkout -b update-travis-build-scripts-2017-09-07-for-master
Switched to a new branch 'update-travis-build-scripts-2017-09-07-for-master'
git add .
git commit -m 'Updated travis build scripts (from rspec-dev)'
[update-travis-build-scripts-2017-09-07-for-master 6cfb4248] Updated travis build scripts (from rspec-dev)
 8 files changed, 11 insertions(+), 10 deletions(-)

==================================================
# rspec-mocks
----------------------------------------
git checkout -b update-travis-build-scripts-2017-09-07-for-master
Switched to a new branch 'update-travis-build-scripts-2017-09-07-for-master'
git add .
git commit -m 'Updated travis build scripts (from rspec-dev)'
[update-travis-build-scripts-2017-09-07-for-master 4b3e4cb2] Updated travis build scripts (from rspec-dev)
 8 files changed, 11 insertions(+), 10 deletions(-)

==================================================
# rspec-rails
----------------------------------------
git checkout -b update-travis-build-scripts-2017-09-07-for-master
Switched to a new branch 'update-travis-build-scripts-2017-09-07-for-master'
./script/before_update_travis_build.sh
Backing up custom Travis config
./script/after_update_travis_build.sh
Restoring custom Travis config
git add .
git commit -m 'Updated travis build scripts (from rspec-dev)'
[update-travis-build-scripts-2017-09-07-for-master 6af2304e] Updated travis build scripts (from rspec-dev)
 7 files changed, 7 insertions(+), 7 deletions(-)

==================================================
# rspec-support
----------------------------------------
git checkout -b update-travis-build-scripts-2017-09-07-for-master
Switched to a new branch 'update-travis-build-scripts-2017-09-07-for-master'
git add .
git commit -m 'Updated travis build scripts (from rspec-dev)'
[update-travis-build-scripts-2017-09-07-for-master f1c07d8] Updated travis build scripts (from rspec-dev)
 8 files changed, 11 insertions(+), 10 deletions(-)

==================================================
# rspec-core
----------------------------------------
fatal: remote error:
  You can't push to git://github.com/rspec/rspec-core.git
  Use https://github.com/rspec/rspec-core.git
Push failed, force? (y/n)
n
git checkout master && git branch -D update-travis-build-scripts-2017-09-07-for-master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
Deleted branch update-travis-build-scripts-2017-09-07-for-master (was 3068f07a).

==================================================
# rspec-expectations
----------------------------------------
fatal: remote error:
  You can't push to git://github.com/rspec/rspec-expectations.git
  Use https://github.com/rspec/rspec-expectations.git
Push failed, force? (y/n)
n
git checkout master && git branch -D update-travis-build-scripts-2017-09-07-for-master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
Deleted branch update-travis-build-scripts-2017-09-07-for-master (was 6cfb4248).

==================================================
# rspec-mocks
----------------------------------------
fatal: remote error:
  You can't push to git://github.com/rspec/rspec-mocks.git
  Use https://github.com/rspec/rspec-mocks.git
Push failed, force? (y/n)
n
git checkout master && git branch -D update-travis-build-scripts-2017-09-07-for-master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
Deleted branch update-travis-build-scripts-2017-09-07-for-master (was 4b3e4cb2).

==================================================
# rspec-rails
----------------------------------------
fatal: remote error:
  You can't push to git://github.com/rspec/rspec-rails.git
  Use https://github.com/rspec/rspec-rails.git
Push failed, force? (y/n)
n
git checkout master && git branch -D update-travis-build-scripts-2017-09-07-for-master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
Deleted branch update-travis-build-scripts-2017-09-07-for-master (was 6af2304e).

==================================================
# rspec-support
----------------------------------------
fatal: remote error:
  You can't push to git://github.com/rspec/rspec-support.git
  Use https://github.com/rspec/rspec-support.git
Push failed, force? (y/n)
n
git checkout master && git branch -D update-travis-build-scripts-2017-09-07-for-master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
Deleted branch update-travis-build-scripts-2017-09-07-for-master (was f1c07d8).

```

</details>

**Comment by JonRowe** [comment]
Hmm of course, you could update origin on all your repos to match up with forks, or patch the code to push to your forks?

**Comment by olleolleolle** [comment]
Fixed by @JonRowe in #188. Thanks!

**Pull request closed without merging**
