### PR TITLE
Quote 3.0 so that it is not zero-suppressed

### PR DESCRIPTION
**Pull request by nobu**

### CODE REVIEW

**Comment by JonRowe** [comment]
:wave: Do you mean so it will match `3.0.1` or `3.1.0` ? We'll be adding the later as a new entry when its released, but I was under the impression the former happened anyway?

**Comment by nobu** [comment]
It’s just an issue of the displayed version number.

**Comment by JonRowe** [comment]
Ah ok

**Comment by dentarg** [comment]
@JonRowe it's an bug with GitHub Actions: https://github.com/actions/runner/issues/849

**Comment by nobu** [comment]
As [the case of 3.10](https://github.com/actions/runner/issues/849#issuecomment-743786370), I think that writing version numbers as floats is a bad habit.

**Pull request merged**
