### PR TITLE
Add 3.0.0-rc1

### PR DESCRIPTION
**Pull request by benoittgt**
~~Waiting for: https://github.com/ruby/setup-ruby/pull/132~~

### CODE REVIEW

**Comment by JonRowe** [comment]
Unleash the PRs! 🎉

**Comment by JonRowe** [comment]
Related PRs:
https://github.com/rspec/rspec-core/pull/2804
https://github.com/rspec/rspec-expectations/pull/1246
https://github.com/rspec/rspec-mocks/pull/1366
https://github.com/rspec/rspec-support/pull/454

**Review by JonRowe — APPROVED** [review]

**Comment by benoittgt** [comment]
oups sorry. I just ran the script. Stoping now

**Comment by JonRowe** [comment]
:joy: Sorry I'd seen you'd done rspec-rails and there was no prs for the others, but I didn't check the timestamp

**Comment by benoittgt** [comment]
Closing in favor of https://github.com/rspec/rspec-dev/pull/267

**Comment by JonRowe** [comment]
@benoittgt #267 targets 4.0 dev

**Comment by benoittgt** [comment]
oook sorry

**Comment by JonRowe** [comment]
All merged thanks @benoittgt!

**Pull request merged**
