### PR TITLE
Update appveyor file to handle Ruby version 2

### PR DESCRIPTION
**Pull request by agileraymond**

### CODE REVIEW

**Comment by myronmarston** [comment]
Thanks.  I opened PRs in the other repos to try running builds with these changes.

**Comment by myronmarston** [comment]
So they all passed except rspec-core: rspec/rspec-core#1861.  Here's the failing app veyor build:

https://ci.appveyor.com/project/rspec/rspec-core/build/341/job/nm85d55j8vy86j33

Can you take a look?

**Comment by rsanchez79** [comment]
Sure I'll take a look.

**Comment by JonRowe** [comment]
Closing as stale

**Pull request closed without merging**
