### PR TITLE
Enable Rubygems on Travis CI

### PR DESCRIPTION
**Pull request by yujinakayama**
Nokogiri requires Rubygems to be enabled on build.

* https://github.com/sparklemotion/nokogiri/blob/v1.6.7.1/ext/nokogiri/extconf.rb#L396
* https://travis-ci.org/rspec/rspec-expectations/jobs/100053387#L2799

### CODE REVIEW

**Comment by yujinakayama** [comment]
* https://github.com/rspec/rspec-core/pull/2151
* https://github.com/rspec/rspec-expectations/pull/884
* https://github.com/rspec/rspec-mocks/pull/1049
* https://github.com/rspec/rspec-rails/pull/1518
* https://github.com/rspec/rspec-support/pull/262

**Comment by yujinakayama** [comment]
Finally all the repos are green :relieved:

**Comment by myronmarston** [comment]
Thank you @yujinakayama!

I wonder if we can have our cake and eat it too by only removing the `--disable=gem` RUBYOPT from the step that installs nokogiri.  For example, if we run `RUBYOPT='' bundle install` would that work?

**Comment by JonRowe** [comment]
I don't think we should do this... There is a PR underway to fix this for nokogiri... #1393, maybe we should help there instead

**Comment by myronmarston** [comment]
Having things green is more important than having `--disable=gem`, so until nokogiri allows it to be installed w/o rubygems, this is reasonable.

That said, as I suggested above, I don't think we care about `--disable=gem` while we're installing dependencies.  Only while running our specs.  So having it set for only some parts of our build would be a reasonable solution, I think.

**Comment by JonRowe** [comment]
How about I merge this and then work on your suggestion?

**Comment by myronmarston** [comment]
:+1:

**Comment by yujinakayama** [comment]
Sorry I was in bed with flu :cold_sweat:

**Comment by myronmarston** [comment]
> Sorry I was in bed with flu

:cry: Sorry to hear that.  I hope you get better soon!

**Pull request merged**
