### PR TITLE
Update appveyor with Ruby 2.3, 2.4 & trunk

### PR DESCRIPTION
**Pull request by MSP-Greg**
Not quite sure if this is the correct file, trying to add Ruby 2.3, 2.4, & trunk to Appveyor tests.

### CODE REVIEW

**Comment by JonRowe** [comment]
I'm happy to add 2.3.x and 2.4.x but we shouldn't add "trunk" (or head ruby in travis parlance) as it's likely to fail often and our windows builds are only a sanity check fos us.

**Comment by MSP-Greg** [comment]
I haven't looked thru all the repos that this is used in, so I don't know how much time another job would add to the build.  

It's being used in several repos, including rubygems/rubygems & ruby/spec, and it seems to track Travis head pretty well.  Ruby core also keeps track of its CI, as they use an mswin build.

I'm fairly active in 'Windows testing', so if there are errors that don't match with Travis, you can always ping me...

So, I'll push /squash a commit that adds it to allow-failure if you'd like.  Otherwise, I can remove it.

**Comment by JonRowe** [comment]
I'd favour removal, we don't really even check them when allow_failures is used, only human after all etc :)

**Comment by MSP-Greg** [comment]
As long as I'm pushing/squashing, do you want Travis updated to 2.2.9, 2.3.6, & 2.4.3?

Forgot to ask in last comment...

**Comment by JonRowe** [comment]
👍 You'll then need to run the rake command to open PRs on other repos.

**Comment by MSP-Greg** [comment]
> You'll then need to run the rake command to open PRs on other repos.

I'll have to look around, I ended up here when I saw the 'auto-generated' note in rspec-core.

BTW, I've got some doc's [here](https://msp-greg.github.io/); it's YARD based, so I do run rspec when I test YARD against trunk (they've changed ripper, since RDoc is now using it).  But that's not rspec master...

> we don't really even check them when allow_failures is used, only human after all etc :)

But I might.  Not necessarily every commit....

**Comment by MSP-Greg** [comment]
I'll get to the rake command after I get all the repos forked...  Thanks, Greg

**Pull request merged**
