### PR TITLE
Update Rubies

### PR DESCRIPTION
**Pull request by pirj**
https://github.com/rspec/rspec-support/pull/406
https://github.com/rspec/rspec-mocks/pull/1323
https://github.com/rspec/rspec-expectations/pull/1175
https://github.com/rspec/rspec-core/pull/2714

### CODE REVIEW

**Comment by pirj** [comment]
http://rubies.travis-ci.org/ubuntu/14.04/x86_64/ruby-2.4.10 is not yet in place, let's wait for a few more days.

**Comment by benoittgt** [comment]
Thanks. Feel free to use the updated rake command when pushing this to other repos.

**Comment by pirj** [comment]
> Feel free to use the updated rake command when pushing this to other repos.

Will do. I couldn't quickly figure out how to do that though 😆

**Comment by pirj** [comment]
Filed https://github.com/travis-ci/travis-rubies/issues/73

**Pull request merged**
